# docker-compose up --build -d

version: '3.8'

services:
    db_actas_fis:
        image: mysql:5.7
        restart: always
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        command: --init-file=/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3333:3306"
        environment:
            MYSQL_DATABASE: actas_fis
            MYSQL_ROOT_USER: carlos-paezf
            MYSQL_USER: carlos-paezf
            MYSQL_ROOT_PASSWORD: 'DOTY0aEnCF2rKcqDfbkL'
            MYSQL_PASSWORD: 'DOTY0aEnCF2rKcqDfbkL'
    # app:
    #     build: .
    #     ports:
    #         - 3000:3000
    #     env_file: .env
    #     depends_on:
    #         - db_actas_fis
